server:
  port: 7000

info:
  groupId: @project.groupId@
  artifactId: @project.artifactId@
  version: @project.version@

spring:
  application:
    name: config
  security:
    user:
      name: config
      password: cf123456
      roles: USER

  profiles:
    active: jdbc
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.198.128:3306/test?Unicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: weilus
      initial-size: 10
      min-idle: 10
      max-active: 100
      max-wait: 6000
      min-evictable-idle-time-millis: 300000
      time-between-eviction-runs-millis: 60000
  cloud:
    config:
      failFast: true
      server:
        jdbc:
          sql: SELECT `key`, `value` FROM cloud_properties WHERE application=? AND profile=? AND label=?
  rabbitmq:
    addresses: 192.168.198.128:5672
    username: guest
    password: guest
logging:
  file: ${log.dir:/data/logs}/${spring.application.name}.log
  level:
    com.weilus: DEBUG
    com.netflix.discovery: ERROR
    org.springframework: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always