server:
  port: 8080
spring:
  application:
    name: es
  data:
    elasticsearch:
      cluster-nodes: 192.168.1.38:32075
      cluster-name: elasticsearch-cluster

logging:
  file: ${log.dir:/data/logs}/${spring.application.name}.log
  level:
    com.weilus: DEBUG
    org.elasticsearch: DEBUG
