kind: Service
apiVersion: v1
metadata:
  name: mysql
  namespace: weilus-cloud
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
    nodePort: 31306  # 30000 - 32767
  type: NodePort
  clusterIP: 10.96.10.101
  selector:
    app: mysql
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mysql
  namespace: weilus-cloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      name: mysql
      namespace: weilus-cloud
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: weilus
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-conf
          mountPath: /etc/mysql/conf.d
        - name: mysql-data
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-conf
        persistentVolumeClaim:
          claimName: mysql-conf-pvc
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-data-pvc