kind: Service
apiVersion: v1
metadata:
  name: rabbitmq
  namespace: weilus-cloud
spec:
  ports:
  - port: 5672
    protocol: TCP
    targetPort: 5672
  clusterIP: 10.96.10.103
  selector:
    app: rabbitmq
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: rabbitmq
  namespace: weilus-cloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      name: rabbitmq
      namespace: weilus-cloud
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: guest
        - name: RABBITMQ_DEFAULT_PASS
          value: guest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5672