kind: Service
apiVersion: v1
metadata:
  name: mysql
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
    nodePort: 31306  # 30000 - 32767
  type: NodePort
  clusterIP: 10.96.10.101
  selector:
    app: weilus.cloud-mysql
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: weilus.cloud-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weilus.cloud-mysql
  template:
    metadata:
      labels:
        app: weilus.cloud-mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: weilus
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-conf
          mountPath: /etc/mysql/conf.d
        - name: mysql-data
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-conf
        hostPath:
          path: /data/mysql/mycnf
      - name: mysql-data
        hostPath:
          path: /data/mysql/mysql-data