kind: Service
apiVersion: v1
metadata:
  name: redis
  namespace: weilus.cloud
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  clusterIP: 10.96.10.102
  selector:
    app: redis
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: redis
  namespace: weilus.cloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    name: redis
    namespace: weilus.cloud
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis
        command:
        - redis-server
        args:
        - --requirepass '123456'
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-data
          mountPath: /data
      volumes:
      - name: redis-data
        hostPath:
          path: /data/redis/redis-data