kind: PersistentVolume
apiVersion: v1
metadata:
  name: redis-data-pv
  namespace: weilus-cloud
spec:
  capacity:
    storage: 200Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: redis-data-pv
  nfs:
    path: /data/nfs-k8s/redis/data
    server: 192.168.1.38
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-data-pvc
  namespace: weilus-cloud
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  storageClassName: redis-data-pv
