kind: ConfigMap
apiVersion: v1
metadata:
  name: gateway
  namespace: weilus-cloud
data:
  application.yml: |-
      spring:
        cloud:
          gateway:
            routes:
            - id: oauth
              uri: lb://oauth
              predicates:
              - Path=/oauth/oauth/token
              filters:
              - Hystrix=oauthCMD
              - StripPrefix=1
            - id: feign-call
              uri: lb://feign-call
              predicates:
              - Path=/feign-call/test/**
              filters:
              - Hystrix=feignCallCMD
              - CheckToken
              - StripPrefix=1
---
kind: Service
apiVersion: v1
metadata:
  name: gateway
  namespace: weilus-cloud
spec:
  ports:
  - port: 8088
    protocol: TCP
    targetPort: 8088
  clusterIP: 10.96.10.96
  selector:
    app: gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: weilus-cloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      name: gateway
      namespace: weilus-cloud
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: registry.cn-hangzhou.aliyuncs.com/weilus923/gateway-k8s:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8088
        volumeMounts:
        - name: config-logs
          mountPath: /data/logs
      volumes:
      - name: config-logs
        hostPath:
          path: /data/logs
      imagePullSecrets:
      - name: docker-registry-key