kind: ConfigMap
apiVersion: v1
metadata:
  name: oauth
  namespace: weilus-cloud
data:
  application.yml: |-
      spring:
        redis:
          database: 0
          host: 10.96.10.102
          password: 123456
        datasource:
          druid:
            driver-class-name: com.mysql.cj.jdbc.Driver
            url: jdbc:mysql://10.96.10.101:3306/test?Unicode=true&characterEncoding=UTF-8&useSSL=false
            username: root
            password: weilus
---
kind: Service
apiVersion: v1
metadata:
  name: oauth
  namespace: weilus-cloud
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: oauth
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: oauth
  namespace: weilus-cloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth
  template:
    metadata:
      name: oauth
      namespace: weilus-cloud
      labels:
        app: oauth
    spec:
      containers:
      - name: oauth
        image: registry.cn-hangzhou.aliyuncs.com/weilus923/auth-k8s:1.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 7000
        volumeMounts:
        - name: config-logs
          mountPath: /data/logs
      volumes:
      - name: config-logs
        hostPath:
          path: /data/logs
      imagePullSecrets:
      - name: docker-registry-key