kind: Service
apiVersion: v1
metadata:
  name: oauth
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: weilus.cloud-oauth
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: weilus.cloud-oauth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weilus.cloud-oauth
  template:
    metadata:
      labels:
        app: weilus.cloud-oauth
    spec:
      containers:
      - name: oauth
        image: registry.cn-hangzhou.aliyuncs.com/weilus923/auth-k8s:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 7000
        volumeMounts:
        - name: config-logs
          mountPath: /data/logs
      volumes:
      - name: config-logs
        hostPath:
          path: /data/logs
      imagePullSecrets:
      - name: docker-registry-key