kind: ConfigMap
apiVersion: v1
metadata:
  name: oauth
  namespace: default
data:
  application.yml: |-
      spring:
        redis:
          database: 0
          host-name: 10.96.10.102
          port: 6379
          pool:
             max-idle: 8
             poolmin-idle: 0
             poolmax-active: 8
             poolmax-wait: -1
        datasource:
          druid:
             driver-class-name: com.mysql.cj.jdbc.Driver
             url: jdbc:mysql://10.96.10.101:3306/test?Unicode=true&characterEncoding=UTF-8&useSSL=false
             username: root
             password: weilus
             initial-size: 10
             min-idle: 10
             max-active: 100
             max-wait: 6000
             min-evictable-idle-time-millis: 300000
             time-between-eviction-runs-millis: 60000
---
kind: Service
apiVersion: v1
metadata:
  name: oauth
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: weilus.cloud-oauth
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: weilus.cloud-oauth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weilus.cloud-oauth
  template:
    metadata:
      labels:
        app: weilus.cloud-oauth
    spec:
      containers:
      - name: oauth
        image: registry.cn-hangzhou.aliyuncs.com/weilus923/auth-k8s:1.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 7000
        volumeMounts:
        - name: config-logs
          mountPath: /data/logs
      volumes:
      - name: config-logs
        hostPath:
          path: /data/logs
      imagePullSecrets:
      - name: docker-registry-key