server:
  port: 8088
info:
  groupId: @project.groupId@
  artifactId: @project.artifactId@
  version: @project.version@

feign:
  hystrix:
    enabled: true
  client:
    config:
      oauth:
        logger-level: full
        connect-timeout: 10000
        read-timeout:  5000

spring:
  profiles:
    active: test

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

logging:
  file: ${log.dir:/data/logs}/${spring.application.name}.log
  level:
    com.feign.clients: DEBUG
    com.weilus: DEBUG
    com.netflix.discovery: ERROR
    org.springframework.security: ERROR

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    restart:
      enabled: true