debug: false
server:
  port: 8081
info:
  groupId: @project.groupId@
  artifactId: @project.artifactId@
  version: @project.version@

spring:
  thymeleaf:
    cache: false

feign:
  okhttp:
    enabled: true
  httpclient:
    enabled: false
  hystrix:
    enabled: true #开启熔断
  client:
    config:
      default:
        loggerLevel: basic
        connect-timeout: 5000
        read-timeout: 5000
      feign-service:
        logger-level: full
        connect-timeout: 30000
        read-timeout:  10000


logging:
  file: ${log.dir:/data/logs}/${spring.application.name}.log
  level:
    root: INFO
    com.feign.clients: DEBUG
    com.weilus: DEBUG
    org.springframework.jdbc: DEBUG
    org.springframework.security: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    restart:
      enabled: true