kind: Service
apiVersion: v1
metadata:
  name: config
spec:
  ports:
  - port: 7000
    protocol: TCP
    targetPort: 7000
  selector:
    app: weilus.cloud-config
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: weilus.cloud-config
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weilus.cloud-config
  template:
    metadata:
      labels:
        app: weilus.cloud-config
    spec:
      containers:
      - name: config
        image: registry.cn-hangzhou.aliyuncs.com/weilus923/config-k8s:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 7000
        volumeMounts:
        - name: config-logs
          mountPath: /data/logs
      volumes:
      - name: config-logs
        hostPath:
          path: /data/logs
      imagePullSecrets:
      - name: docker-registry-key