kind: Service
apiVersion: v1
metadata:
  name: admin
  namespace: weilus.cloud
spec:
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8888
    nodePort: 31888
  type: NodePort
  selector:
    app: admin
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: admin
  namespace: weilus.cloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
      - name: admin
        image: registry.cn-hangzhou.aliyuncs.com/weilus923/admin-k8s:1.0
        imagePullPolicy: IfNotPresent
        env:
        - name: spring.boot.admin.discovery.services
          value: oauth,feign-call,feign-service,admin
        ports:
        - containerPort: 8888
        volumeMounts:
        - name: config-logs
          mountPath: /data/logs
      volumes:
      - name: config-logs
        hostPath:
          path: /data/logs
      imagePullSecrets:
      - name: docker-registry-key