kind: ConfigMap
apiVersion: v1
metadata:
  name: feign-service
  namespace: default
data:
  test.name: 张学友
---
kind: Service
apiVersion: v1
metadata:
  name: feign-service
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: weilus.cloud-feign-service
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: weilus.cloud-feign-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weilus.cloud-feign-service
  template:
    metadata:
      labels:
        app: weilus.cloud-feign-service
    spec:
      containers:
      - name: feign-service
        image: registry.cn-hangzhou.aliyuncs.com/weilus923/feign-hystrix-k8s:1.0
        imagePullPolicy: IfNotPresent
        env:
        - name: spring.application.name
          value: feign-service
        ports:
        - containerPort: 8081
        volumeMounts:
        - name: config-logs
          mountPath: /data/logs
      volumes:
      - name: config-logs
        hostPath:
          path: /data/logs
      imagePullSecrets:
      - name: docker-registry-key