kind: ConfigMap
apiVersion: v1
metadata:
  name: feign-call
  namespace: weilus-cloud
data:
  test.name: 张学友
---
kind: Service
apiVersion: v1
metadata:
  name: feign-call
  namespace: weilus-cloud
spec:
  ports:
  - port: 8081
    targetPort: 8081
  clusterIP: None
  selector:
    app: feign-call
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: feign-call
  namespace: weilus-cloud
spec:
  replicas: 1
  template:
    metadata:
      namespace: weilus-cloud
      labels:
        app: feign-call
    spec:
      containers:
      - name: k8s-feign-call
        image: registry.cn-hangzhou.aliyuncs.com/weilus923/feign-hystrix-k8s:1.0
        imagePullPolicy: IfNotPresent
        env:
        - name: spring.application.name
          value: feign-call
        ports:
        - containerPort: 8081
        volumeMounts:
        - name: config-logs
          mountPath: /data/logs
      volumes:
      - name: config-logs
        hostPath:
          path: /data/logs
      imagePullSecrets:
      - name: docker-registry-key